# create pipeline
name: bh app containarization pipeline
# trigger - when this pipeline should start
on:
  push:
    branches:
      - "dev"
# jobs
jobs:
  bh-image-build:
    runs-on: ubuntu-latest
    # this server will be provisioned by github backend for this job
    steps:
      - name: run some basic commands on above servers
        run: |
          uname -r
          whoami
          cat /etc/os-release
          docker version
          docker-compose version
      - name: using pre-design github workflow to get copy gitrepo code to runners machine
        uses: actions/checkout@v4

      - name: verify github code and use docker compose to build and create
        run: |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps
          sonarqube-scanner --version
      - name: Check the deployed service URL
        run: |
          curl -f http://localhost:1234/health.html
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: rebuild image in docker hub format and push it docker hub
        run: |
          echo "need to build"
          echo "and push to docker hub"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: varmadbk/bh-webgit:v2
      - name: docker logout
        run: docker logout
