# create pipeline
name: bh app containarization pipeline
# trigger - when this pipeline should start
on:
  push:
    branches:
      - "dev"
# jobs
jobs:
  bh-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run: |
          docker version
          sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4
      
      - name: run sonar locally
        run: |
          pwd
          sonar-scanner -D"sonar.projectKey=bh-test-py" -D"sonar.sources=." -D"sonar.host.url=http://44.219.46.64:9000" -D"sonar.token=sqp_7255566d38192f9d2253791c7c31ec72798a5fb8"
  bh-build-job:
    runs-on: macos-latest
    needs: bh-sast-job
    steps:
      - name: general message
        run: |
          echo "python version is"
          python -V
          echo "test"