# create pipeline
name: bh app containarization pipeline
# trigger - when this pipeline should start
on:
  push:
    branches:
      - "dev"
# jobs
jobs:
  bh-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run: |
          docker version
          sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4
      
      - name: run sonar locally
        run: |
          pwd
          sonar-scanner -D"sonar.projectKey=bh-test-py" -D"sonar.sources=." -D"sonar.host.url=http://44.219.46.64:9000" -D"sonar.token=sqp_7255566d38192f9d2253791c7c31ec72798a5fb8"
      - name: use upload atrifacts
        uses: actions/upload-artifact@v4
        with:
          name: bh-artifact
          path: |
            .
            !**/.git*
            !**/*.md
  bh-build-job:
    runs-on: ubuntu-latest
    needs: bh-sast-job
    steps:
      - name: general message
        run: |
          echo "checking docker details"
          docker version
          docker-compose version
      - name: downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: bh-artifact
          path: .
      - name: docker compose to build and test
        run: |
          ls -a
          docker-compose up -d --build
          sleep 2
          docker-compose ps
      - name: verify health check page
        run: |
          echo "checking health"
          curl -f http://localhost:1234/health.html

    
          