# create pipeline
name: bh app containarization pipeline
# trigger - when this pipeline should start
on:
  push:
    branches:
      - "dev"
# jobs
jobs:
  bh-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run: |
          docker version
          sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4
      
      - name: run sonar locally
        run: |
          pwd
          sonar-scanner -D"sonar.projectKey=bh-test-py" -D"sonar.sources=." -D"sonar.host.url=http://44.219.46.64:9000" -D"sonar.token=sqp_7255566d38192f9d2253791c7c31ec72798a5fb8"
      - name: use upload atrifacts
        uses: actions/upload-artifact@v4
        with:
          name: bh-artifact
          path: |
            .
            !**/.git*
            !**/*.md
  bh-build-job:
    runs-on: ubuntu-latest
    needs: bh-sast-job
    steps:
      - name: general message
        run: |
          echo "checking docker details"
          docker version
          docker-compose version
      - name: downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: bh-artifact
          path: .
      - name: docker compose to build and test
        run: |
          ls -a
          docker-compose up -d --build
          sleep 2
          docker-compose ps
      - name: verify health check page
        run: |
          echo "checking health"
          curl -f http://localhost:1234/health.html
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: push image
        run: |
          docker tag bh-devweb:v3 751136288263.dkr.ecr.us-east-1.amazonaws.com/bmo-webui-app:bhv4
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 751136288263.dkr.ecr.us-east-1.amazonaws.com
          docker push 751136288263.dkr.ecr.us-east-1.amazonaws.com/bmo-webui-app:bhv4

          

    
          